#!/usr/bin/env python3
"""Generate checked OpenAPI, TypeScript wire types, and HTTP composition."""

from __future__ import annotations

import argparse
import json
import subprocess
import tempfile
from pathlib import Path

from doc_evidence.api.app import create_contract_app

ROOT = Path(__file__).parents[1]
OPENAPI_PATH = ROOT / "contracts" / "openapi.v1.json"
SCHEMA_PATH = ROOT / "web" / "src" / "api" / "generated" / "schema.ts"
CLIENT_PATH = ROOT / "web" / "src" / "api" / "generated" / "client.ts"
GENERATOR = ROOT / "web" / "node_modules" / ".bin" / "openapi-typescript"

CLIENT_SOURCE = """// Generated by scripts/generate-contracts.py. Do not edit.\nimport createClient from \"openapi-fetch\";\n\nimport type { paths } from \"./schema\";\n\nexport function createGeneratedClient(baseUrl: string, launchToken: string) {\n  return createClient<paths>({\n    baseUrl,\n    headers: { Authorization: `Bearer ${launchToken}` },\n  });\n}\n\nexport type GeneratedClient = ReturnType<typeof createGeneratedClient>;\n"""


def _openapi_bytes() -> bytes:
    schema = create_contract_app().openapi()
    return (json.dumps(schema, indent=2, sort_keys=True) + "\n").encode("utf-8")


def _generate_types(openapi_path: Path, output_path: Path) -> None:
    if not GENERATOR.is_file():
        raise SystemExit(
            "openapi-typescript is unavailable; run npm install --prefix web first"
        )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [str(GENERATOR), str(openapi_path), "--output", str(output_path)],
        check=True,
        cwd=ROOT,
    )


def _check(expected: Path, generated: Path) -> bool:
    return expected.is_file() and expected.read_bytes() == generated.read_bytes()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory() as directory:
        temporary = Path(directory)
        openapi = temporary / "openapi.v1.json"
        schema = temporary / "schema.ts"
        client = temporary / "client.ts"
        openapi.write_bytes(_openapi_bytes())
        _generate_types(openapi, schema)
        client.write_text(CLIENT_SOURCE, encoding="utf-8")
        if args.check:
            drift = [
                label
                for label, expected, generated in (
                    ("OpenAPI", OPENAPI_PATH, openapi),
                    ("TypeScript schema", SCHEMA_PATH, schema),
                    ("TypeScript client", CLIENT_PATH, client),
                )
                if not _check(expected, generated)
            ]
            if drift:
                print("generated contract drift: " + ", ".join(drift))
                return 1
            print("generated contracts are current")
            return 0
        for destination, generated in (
            (OPENAPI_PATH, openapi),
            (SCHEMA_PATH, schema),
            (CLIENT_PATH, client),
        ):
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(generated.read_bytes())
        print("generated OpenAPI, TypeScript schema, and typed client")
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
